pipeline {
    agent any

    environment {
        GITHUB_TOKEN_IS_HERE = credentials('GITHUB_TOKEN') // from Jenkins credentials
    }

    stages {
        stage('Build and Run Docker') {
            steps {
                script {
                    def imageName = "my-python-test-image"
                    echo "Build and Run Docker."
                    if (isUnix()) {
                        // For Linux/macOS
                        sh "docker build -t ${imageName} -f tests/Dockerfile ."
                        sh "docker run --rm ${imageName}"
                    } else {
                        // For Windows
                        echo "Start of building docker image."
                        bat "docker build --no-cache -t my-python-test-image -f tests/Dockerfile ."
//                      bat "docker build -t ${imageName} -f Docker/Dockerfile ."
                        echo "Dcoker image is built."
                        bat "docker run --rm ${imageName}"
                        echo "end of of building docker image."
                    }
                }
            }
        }
    }

     post {
        success {
            emailext (
                subject: "✅ Build Success - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "Good news! Build succeeded.\n\nBuild URL: ${env.BUILD_URL}",
                to: "akhilagangadharuppin@gmail.com"
            )
        }

        failure {
            emailext (
                subject: "❌ Build Failure - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "The build failed.\n\nBuild URL: ${env.BUILD_URL}",
                to: "akhilagangadharuppin@gmail.com"
            )
        }
     }
}
