pipeline {
    agent any

    environment {
        GITHUB_TOKEN_IS_HERE = credentials('GITHUB_TOKEN') // from Jenkins credentials
    }

    stages {
        stage('Build and Run Docker') {
            steps {
                script {
                    def imageName = "my-python-test-image"
                    echo "Build and Run Docker."
                    if (isUnix()) {
                        // For Linux/macOS
                        sh "docker build -t ${imageName} -f Docker/Dockerfile ."
                        sh "docker run --rm ${imageName}"
                    } else {
                        // For Windows
                        echo "Start of building docker image."
                        bat "docker build -t ${imageName} -f Docker/Dockerfile ."
                        echo "Dcoker image is built."
                        bat "docker run --rm ${imageName}"
                        echo "end of of building docker image."
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Build and tests successful.'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
