pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to the Dockerfile directory
                    dir('Docker') {
                        dockerImage = docker.build("python-selenium-tests")
                    }
                }
            }
        }

        stage('Run Tests in Docker') {
            steps {
                script {
                    dockerImage.run()
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Build and tests successful.'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
