pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    if (isUnix()) {
                        echo 'linux OS'
                        sh 'git clone https://github.com/GangadharUppin/python_selenium_git_code.git'
                    } else {
                        echo 'window os'
                        bat 'git clone https://github.com/GangadharUppin/python_selenium_git_code.git'
                    }
                }
            }
        }
    }
}
