pipeline {
    agent any

//     environment {
//         REPO_URL = 'https://github.com/GangadharUppin/python_selenium_git_code.git'
//     }

    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning repo!"
            }
        }

        stage('Print Message') {
            steps {
                echo "Repository cloned successfully!"
            }
        }
    }
}
